# Generated by Django 5.2.12 on 2026-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Consulta de búsqueda')),
                ('sources', models.CharField(default='arxiv,elibrary,scopus,wos', max_length=256, verbose_name='Fuentes buscadas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('total_found', models.IntegerField(default=0, verbose_name='Total encontrados')),
                ('total_saved', models.IntegerField(default=0, verbose_name='Total guardados/actualizados')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
            ],
            options={
                'verbose_name': 'Trabajo de búsqueda',
                'verbose_name_plural': 'Trabajos de búsqueda',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('authors', models.TextField(blank=True, default='', verbose_name='Autores')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('journal', models.CharField(blank=True, default='', max_length=512, verbose_name='Revista / Conferencia')),
                ('doi', models.CharField(blank=True, help_text='Identificador de objeto digital (puede ser nulo si no está disponible).', max_length=512, null=True, unique=True, verbose_name='DOI')),
                ('url', models.URLField(blank=True, default='', max_length=2048, verbose_name='URL')),
                ('source_db', models.CharField(choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('arxiv', 'arXiv'), ('elibrary', 'eLIBRARY'), ('unknown', 'Desconocido')], default='unknown', max_length=20, verbose_name='Base de datos fuente')),
                ('source_id', models.CharField(blank=True, default='', help_text='ID interno del artículo en la base de datos de origen.', max_length=256, verbose_name='ID en la fuente')),
                ('abstract_original', models.TextField(blank=True, default='', help_text='Texto del abstract en el idioma original del artículo.', verbose_name='Abstract original')),
                ('language_original', models.CharField(blank=True, default='', help_text='Código ISO 639-1 del idioma original (ej: ru, en).', max_length=10, verbose_name='Idioma original')),
                ('keywords', models.TextField(blank=True, default='', help_text='Palabras clave separadas por comas.', verbose_name='Palabras clave')),
                ('article_type', models.CharField(choices=[('theoretical', 'Teórico'), ('experimental', 'Experimental'), ('review', 'Revisión / Survey'), ('mixed', 'Teórico-Experimental'), ('unknown', 'No determinado')], default='unknown', max_length=20, verbose_name='Tipo de artículo')),
                ('title_es', models.TextField(blank=True, default='', verbose_name='Título en español')),
                ('title_en', models.TextField(blank=True, default='', verbose_name='Título en inglés')),
                ('abstract_es', models.TextField(blank=True, default='', verbose_name='Abstract en español')),
                ('abstract_en', models.TextField(blank=True, default='', verbose_name='Abstract en inglés')),
                ('ai_summary', models.TextField(blank=True, default='', help_text='Resumen generado por el modelo de lenguaje.', verbose_name='Resumen IA')),
                ('ai_analysis', models.TextField(blank=True, default='', help_text='Análisis estructurado: metodología, resultados clave, relevancia para ЭМС.', verbose_name='Análisis IA')),
                ('ai_processed', models.BooleanField(default=False, help_text='Indica si el artículo ha sido analizado por Ollama.', verbose_name='Procesado por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['source_db'], name='articles_ar_source__26e9c7_idx'), models.Index(fields=['year'], name='articles_ar_year_717df9_idx'), models.Index(fields=['article_type'], name='articles_ar_article_e4adb6_idx'), models.Index(fields=['ai_processed'], name='articles_ar_ai_proc_e7c742_idx')],
            },
        ),
    ]
