# Generated by Django 5.2.12 on 2026-03-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='search_jobs', to='articles.article', verbose_name='Artículos encontrados'),
        ),
    ]
