# Generated by Django 5.2.12 on 2026-03-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_job_articles_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_ru',
            field=models.TextField(blank=True, default='', verbose_name='Abstract en ruso'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.TextField(blank=True, default='', verbose_name='Título en ruso'),
        ),
    ]
