# Generated by Django 5.2.12 on 2026-03-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_add_russian_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_analysis_en',
            field=models.TextField(blank=True, default='', verbose_name='Análisis IA (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_analysis_es',
            field=models.TextField(blank=True, default='', verbose_name='Análisis IA (ES)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_analysis_ru',
            field=models.TextField(blank=True, default='', verbose_name='Análisis IA (RU)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_summary_en',
            field=models.TextField(blank=True, default='', verbose_name='Resumen IA (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_summary_es',
            field=models.TextField(blank=True, default='', verbose_name='Resumen IA (ES)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_summary_ru',
            field=models.TextField(blank=True, default='', verbose_name='Resumen IA (RU)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', help_text='Análisis IA principal — campo legacy, usar ai_analysis_*.', verbose_name='Análisis IA (legacy)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='Resumen IA principal — campo legacy, usar ai_summary_*.', verbose_name='Resumen IA (legacy)'),
        ),
    ]
