# Generated by Django 5.2.12 on 2026-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_add_multilang_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nuevo cuaderno', max_length=255, verbose_name='Título del cuaderno')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('articles', models.ManyToManyField(blank=True, related_name='notebooks', to='articles.article', verbose_name='Artículos en el cuaderno')),
            ],
            options={
                'verbose_name': 'Cuaderno',
                'verbose_name_plural': 'Cuadernos',
                'ordering': ['-created_at'],
            },
        ),
    ]
