# Generated by Django 5.2.12 on 2026-03-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_add_notebook_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchjob',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to='articles.notebook', verbose_name='Cuaderno asociado'),
        ),
    ]
