# Generated by Django 5.2.12 on 2026-04-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_searchjob_notebook_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_error',
            field=models.TextField(blank=True, default='', help_text='Mensaje del último error ocurrido durante el análisis IA.', verbose_name='Último error de análisis IA'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_error_code',
            field=models.CharField(blank=True, default='', help_text='Código tipificado: rate_limited, auth_error, model_unavailable, timeout, no_content, unknown.', max_length=30, verbose_name='Código de error IA'),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_processing',
            field=models.BooleanField(default=False, help_text='Indica que el artículo está siendo analizado en background.', verbose_name='Análisis en curso'),
        ),
    ]
